# Site settings
name: 大西君的博客
email: wnh_008@163.com
author: M/J
url: http://blog.marvingalaxy.info
resume_site: http://blog.marvingalaxy.info/me/
github: https://github.com/banlangen/
baseurl: ""  #根目录
description: I'm bad, that's good, I will never be good, that's not bad.
motto: 我们笑着说再见，却深知再见遥遥无期。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: becomming stronger。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : banlangen
